### PR TITLE
Fix #199

### LINKED ISSUE #199: WCVB logo?
@sroosa : Do we have a WCVB logo for the footer? There's nothing at the img src we're using right now.

### PR DESCRIPTION
**Pull request by mccalluc**
@foo4thought ?

### CODE REVIEW

**Comment by foo4thought** [comment]
seriously?  I hate that logo and cannot - in good conscience - merge this branch.

**Comment by caseyedavis12** [comment]
@foo4thought: lol

________________________________

**Comment by mccalluc** [comment]
@foo4thought : Would changing it to grayscale and rescaling address your concerns? This comes from @sroosa: Do you believe there is a better option?

**Comment by sroosa** [comment]
@mccalluc : Sorry that must have been the raw file. I didn't save the greyscaled resized one that we planned to use on the website along with the other logos. I can make those changes now and resend.

**Comment by foo4thought** [comment]
OMG - you guys are serious.  @caseyedavis12 got me figured out because I was pushing back on the need for such "review."  LOL

**Comment by mccalluc** [comment]
I would sincerely appreciate it threads here could be reserved for discussion of the issues. "LOL" adds absolutely nothing and is a waste of my time. There's already a lot of crap I'll need to wade through to get this site in good working order. If you don't believe you're the appropriate person to review a request, please just assign it to the right person. Thanks.

Closing this because Sadie has a better image, and I'll put that in a new PR.

**Pull request closed without merging**
